name: DX9 FFP Config Regression

on:
  pull_request:
    paths:
      - 'patches/**/proxy/**'
      - 'patches/**/remix-comp/**'
      - '**/remix-comp-proxy.ini'
      - '**/renderer.cpp'
  workflow_dispatch:

jobs:
  call:
    uses: ./.github/workflows/_dx9-ffp-regression.yml
    with:
      ini_path: patches/TombRaiderLegend/remix-comp/assets/remix-comp-proxy.ini
      renderer_path: patches/TombRaiderLegend/remix-comp/src/comp/modules/renderer.cpp
