name: PR Automation - Merge

on:
  pull_request_target:
    types: [labeled, synchronize, opened, reopened]
  check_suite:
    types: [completed]
  schedule:
    - cron: '*/30 * * * *'

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  call:
    uses: ./.github/workflows/_automerge.yml
    secrets: inherit
