name: PR Automation - Open PR on Push

on:
  push:
    branches-ignore: [main]
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  call:
    uses: ./.github/workflows/_auto-open-pr.yml
    secrets: inherit
